Part 10
lunulu/testguru pull request #10
Opened 2022-09-17 14:23 UTC by lunulu

2022-09-17 17:14 UTC, BubuntuClu requested changes

2022-09-17 17:14 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to path
можно без переменной

2022-09-17 17:14 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
куку бы тоже очистить

2022-09-17 17:14 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
а если флэш сообщение с другим ключем будет? то для этого нужно будет отдельный хэлпер делать? не очень хороший подход. надо сделать универсальный метод, который будет отображать все флэши(не важно сколько их задано и какие ключи)

2022-09-17 17:14 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирует путь на 7ой строке

2022-09-17 17:14 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирует путь на 6ой строке

2022-09-17 17:14 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email", null: false
нужен уникальный индекс на поле почты

2022-09-17 18:07 UTC, lunulu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
По заданию, нужно сделать хелпер. Я честно пытался:
![Снимок экрана 2022-09-17 в 21 01 27](https://user-images.githubusercontent.com/65171793/190870549-01d5afcd-290a-4053-9960-aabe076a5bb1.png)
![Снимок экрана 2022-09-17 в 21 01 36](https://user-images.githubusercontent.com/65171793/190870553-dd7280e6-7697-4012-8245-f5adce289826.png)
![Снимок экрана 2022-09-17 в 21 01 45](https://user-images.githubusercontent.com/65171793/190870554-19049a83-255e-4204-8aec-ba170f3056ea.png)


Но почему-то это не работает.
https://stackoverflow.com/questions/12345065/rails-flash-message-helper - тоже не помогло

В итоге сделал без проблем через partial

2022-09-17 18:08 UTC, lunulu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
Еще конечно вот это есть, но я не стал пока это пробовать
https://gist.github.com/elomarns/1189398

2022-09-17 18:12 UTC, lunulu commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
Теперь очищаю куки с запрашиваемым адресом после удачного логина.

Я пытался удалить  _test_guru_session, но видимо это невозможно:
http://maverickblogging.com/logout-is-broken-by-default-ruby-on-rails-web-applications/

2022-09-18 16:26 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
хэлпер должен вернуть какой-то результат. в реализации через `each` что является результатом блока?

2022-09-18 16:27 UTC, BubuntuClu commented on app/views/shared/_flashes.html.erb
> +<% flash.each do |type, msg| %>
переделай на хэлпер.

2022-09-18 16:27 UTC, BubuntuClu commented on app/views/shared/_flashes.html.erb
> +  <p class="flash <%= type %>"><%= msg %></p>
проверяй что сообщение действительно есть в этом ключе

2022-09-18 17:01 UTC, lunulu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
content_tag :p, message, class: "flash #{key}"

2022-09-18 17:10 UTC, lunulu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
Это по идее должен быть массив тэгов p

2022-09-18 17:34 UTC, lunulu commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[:alert], class: 'flash alert' if flash[:alert]
А, вроде понял, но не до конца...

2022-09-18 17:38 UTC, merged